/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import BBDD.Conexion;
import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class ventanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPrincipal
     */
    public ventanaPrincipal() {
        initComponents();
        bbdd= new Conexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelpizza = new javax.swing.JPanel();
        jButtonAñadirPizza = new javax.swing.JButton();
        jButtonEliminarPizza = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombrePizza = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPrecioPizza = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldtamañoPizza = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanelingredientes = new javax.swing.JPanel();
        jButtonAñadirIngrediente = new javax.swing.JButton();
        jButtonEliminarIngrediente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNombreIngrediente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPrecioIngrediente = new javax.swing.JTextField();
        jButtonMostartablaPizza = new javax.swing.JButton();
        jPanelclientes = new javax.swing.JPanel();
        jButtonAñadirCliente = new javax.swing.JButton();
        jButtonEliminarClietne = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNombreCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldtelefonoCleinte = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldDireccionCleinte = new javax.swing.JTextField();
        jButtonMostartablaIngredientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelpizza.setBorder(javax.swing.BorderFactory.createTitledBorder("Pizzas"));

        jButtonAñadirPizza.setText("Añadir");
        jButtonAñadirPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirPizzaActionPerformed(evt);
            }
        });

        jButtonEliminarPizza.setText("Eliminar");
        jButtonEliminarPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarPizzaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Precio:");

        jLabel3.setText("Tamaño");

        jButton1.setText("MostrarTabla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelpizzaLayout = new javax.swing.GroupLayout(jPanelpizza);
        jPanelpizza.setLayout(jPanelpizzaLayout);
        jPanelpizzaLayout.setHorizontalGroup(
            jPanelpizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelpizzaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNombrePizza, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPrecioPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldtamañoPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelpizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonEliminarPizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAñadirPizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelpizzaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanelpizzaLayout.setVerticalGroup(
            jPanelpizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelpizzaLayout.createSequentialGroup()
                .addGroup(jPanelpizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelpizzaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAñadirPizza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEliminarPizza))
                    .addGroup(jPanelpizzaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanelpizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldNombrePizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldPrecioPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldtamañoPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelingredientes.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingredientes"));

        jButtonAñadirIngrediente.setText("Añadir");
        jButtonAñadirIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirIngredienteActionPerformed(evt);
            }
        });

        jButtonEliminarIngrediente.setText("Eliminar");
        jButtonEliminarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarIngredienteActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre:");

        jLabel5.setText("Precio:");

        jButtonMostartablaPizza.setText("MostrarTabla");
        jButtonMostartablaPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostartablaPizzaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelingredientesLayout = new javax.swing.GroupLayout(jPanelingredientes);
        jPanelingredientes.setLayout(jPanelingredientesLayout);
        jPanelingredientesLayout.setHorizontalGroup(
            jPanelingredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelingredientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPrecioIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelingredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonEliminarIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAñadirIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelingredientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonMostartablaPizza)
                .addContainerGap())
        );
        jPanelingredientesLayout.setVerticalGroup(
            jPanelingredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelingredientesLayout.createSequentialGroup()
                .addGroup(jPanelingredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelingredientesLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanelingredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldNombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldPrecioIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelingredientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAñadirIngrediente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEliminarIngrediente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMostartablaPizza)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelclientes.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes"));

        jButtonAñadirCliente.setText("Añadir");
        jButtonAñadirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirClienteActionPerformed(evt);
            }
        });

        jButtonEliminarClietne.setText("Eliminar");
        jButtonEliminarClietne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarClietneActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombre:");

        jLabel7.setText("Telefono:");

        jLabel8.setText("Direccion:");

        jButtonMostartablaIngredientes.setText("MostrarTabla");
        jButtonMostartablaIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostartablaIngredientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelclientesLayout = new javax.swing.GroupLayout(jPanelclientes);
        jPanelclientes.setLayout(jPanelclientesLayout);
        jPanelclientesLayout.setHorizontalGroup(
            jPanelclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelclientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonMostartablaIngredientes)
                .addContainerGap())
            .addGroup(jPanelclientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAñadirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelclientesLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldtelefonoCleinte, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDireccionCleinte, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminarClietne)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelclientesLayout.setVerticalGroup(
            jPanelclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelclientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAñadirCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelclientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldtelefonoCleinte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldDireccionCleinte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarClietne))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMostartablaIngredientes)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelpizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelingredientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelclientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelpizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelingredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelclientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAñadirPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirPizzaActionPerformed
        String nombre=jTextFieldNombrePizza.getText();
        double precio=Double.parseDouble(jTextFieldPrecioPizza.getText());
        int tamanio=Integer.parseInt(jTextFieldtamañoPizza.getText());
        if(bbdd.añadirPizza(nombre, precio, tamanio)>0){
            JOptionPane.showMessageDialog(this, "La Pizza se añadido con exito");
        }else{
            JOptionPane.showMessageDialog(this, "La Pizza Ya Existe");
        }
    }//GEN-LAST:event_jButtonAñadirPizzaActionPerformed

    private void jButtonAñadirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirClienteActionPerformed
        String nombre=jTextFieldNombreCliente.getText();
        String telefono=jTextFieldtelefonoCleinte.getText();
        String direccion=jTextFieldDireccionCleinte.getText();
        if(bbdd.añadirCliente(telefono, nombre, direccion)>0){
            JOptionPane.showMessageDialog(this, "El cliente se añadido con exito");
        }else{
            JOptionPane.showMessageDialog(this, "El cliente Ya Existe");
        }
    }//GEN-LAST:event_jButtonAñadirClienteActionPerformed

    private void jButtonEliminarClietneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarClietneActionPerformed
        String telefono=jTextFieldtelefonoCleinte.getText();
        if(bbdd.eliminarCliente(telefono)>0){
            JOptionPane.showMessageDialog(this, "El cliente se elimino con exito");
        }else{
            JOptionPane.showMessageDialog(this, "El cliente no Existe");
        }
    }//GEN-LAST:event_jButtonEliminarClietneActionPerformed

    private void jButtonAñadirIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirIngredienteActionPerformed
        String nombre=jTextFieldNombreIngrediente.getText();
        double precio=Double.parseDouble(jTextFieldPrecioIngrediente.getText());
        if(bbdd.añadirIngrediente(nombre, precio)>0){
            JOptionPane.showMessageDialog(this, "El Ingrediente se añadido con exito");
        }else{
            JOptionPane.showMessageDialog(this, "El IngredienteYa Existe");
        }
    }//GEN-LAST:event_jButtonAñadirIngredienteActionPerformed

    private void jButtonEliminarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarIngredienteActionPerformed
        String nombre=jTextFieldNombreIngrediente.getText();
        if(bbdd.eliminaIngredientes(nombre)>0){
            JOptionPane.showMessageDialog(this, "El Ingrediente se elimino con exito");
        }else{
            JOptionPane.showMessageDialog(this, "El Ingrediente no Existe");
        }
    }//GEN-LAST:event_jButtonEliminarIngredienteActionPerformed

    private void jButtonEliminarPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarPizzaActionPerformed
         String nombre=jTextFieldNombrePizza.getText();
        if(bbdd.eliminaPizza(nombre)>0){
            JOptionPane.showMessageDialog(this, "La Pizza se elimino con exito");
        }else{
            JOptionPane.showMessageDialog(this, "La Pizza no Existe");
        }
    }//GEN-LAST:event_jButtonEliminarPizzaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String pizza =bbdd.MostarTablas("Nombre", "pizza");
        JOptionPane.showMessageDialog(this, pizza);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonMostartablaPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostartablaPizzaActionPerformed
       String ingredientes =bbdd.MostarTablas("Nombre", "Ingredientes");
        JOptionPane.showMessageDialog(this, ingredientes);
    }//GEN-LAST:event_jButtonMostartablaPizzaActionPerformed

    private void jButtonMostartablaIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostartablaIngredientesActionPerformed
        String ingredientes =bbdd.MostarTablas("Telefono", "cliente");
        JOptionPane.showMessageDialog(this, ingredientes);
    }//GEN-LAST:event_jButtonMostartablaIngredientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPrincipal().setVisible(true);
            }
        });
    }
    private Conexion bbdd;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAñadirCliente;
    private javax.swing.JButton jButtonAñadirIngrediente;
    private javax.swing.JButton jButtonAñadirPizza;
    private javax.swing.JButton jButtonEliminarClietne;
    private javax.swing.JButton jButtonEliminarIngrediente;
    private javax.swing.JButton jButtonEliminarPizza;
    private javax.swing.JButton jButtonMostartablaIngredientes;
    private javax.swing.JButton jButtonMostartablaPizza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelclientes;
    private javax.swing.JPanel jPanelingredientes;
    private javax.swing.JPanel jPanelpizza;
    private javax.swing.JTextField jTextFieldDireccionCleinte;
    private javax.swing.JTextField jTextFieldNombreCliente;
    private javax.swing.JTextField jTextFieldNombreIngrediente;
    private javax.swing.JTextField jTextFieldNombrePizza;
    private javax.swing.JTextField jTextFieldPrecioIngrediente;
    private javax.swing.JTextField jTextFieldPrecioPizza;
    private javax.swing.JTextField jTextFieldtamañoPizza;
    private javax.swing.JTextField jTextFieldtelefonoCleinte;
    // End of variables declaration//GEN-END:variables
}
